### PR TITLE
Snagit 2020.1.1 drop 

### PR DESCRIPTION
**Pull request by theeagle**

### CODE REVIEW

**Comment by aprilnoren** [comment]
I see the `ShortcutRecorder.strings` files were deleted.  Are we refereincing these in some other way? Also the files were deleted but I don't see a reference to them deleted in the project file.  Were we just not were referencing those files?

**Comment by theeagle** [comment]
@jballance and I were both looking at these, I rebased our localization branch on master which brought along a separate merge from Camtasia. So, yeah, we'll have to look closer.

**Comment by jballance** [comment]
I think you'll want to pull out that first commit of mine, that was me trying to make changes and seeing if they helped but didn't quite finish playing with. it wasn't anything I intended to make into master

**Comment by theeagle** [comment]
I think it's actually much better, all of that stuff was superfluous anyway.

**Review by aprilnoren — CHANGES_REQUESTED** [review]
Hmm, I checked some of the strings that I thought to be associated with the ShortcutRecorder.strings and building this branch I now see English in some of those areas.

Bildschirmfoto 2020-01-07 um 1 59 42 PM

**Comment by theeagle** [comment]
closing this for now since a few different unintended things got combined

**Pull request closed without merging**
