### PR TITLE
Move strings files up a level

### PR DESCRIPTION
**Pull request by jballance**
Moved strings files up a directory to resolve an issue with the importer being able to find them. Did a practice export/import of strings and they imported alright, seen here: https://github.com/TechSmith/ShortcutRecorder/pull/18

### CODE REVIEW

**Comment by jballance** [comment]
@theeagle bumping this, hoping to get this merged before Camtasia's next drop (so this week). 
I did another pseudo drop after changing the file encodings, you can see the diff here:
https://github.com/TechSmith/ShortcutRecorder/compare/master...TechSmith:localization/drop-major-01-28-2020
and things look like they are in their proper language? unless you see anything that's off.
also, if there are any translations you are suspicious of, we can make a list and give it to Victoria

**Comment by theeagle** [comment]
Sorry for the delay, it seems a little weird to move the lproj folders out of Resources, as that's the standard pattern.

**Comment by theeagle** [comment]
In https://github.com/TechSmith/ShortcutRecorder/pull/18/files, I'm still not clear on what strings changed because those top files just say "binary file not shown", so any guidance on what to test or look for would be helpful.

**Comment by jballance** [comment]
that's fair. I guess we wouldn't have to move the files if the xliffs would write out with the correct src path. do you have any ideas on why it currently writes out as `<file original="en.lproj/ShortcutRecorder.strings"` instead of `Resources/en.lproj/...`?

as far as what to look for, I did a new "drop" just this morning, and that would be the better one to look at (https://github.com/TechSmith/ShortcutRecorder/compare/master...TechSmith:localization/drop-major-01-28-2020) and ignore #18 
and if you look at the new diff, you'll see (below the binary file not shown) where we now have fr, de, and zh strings files at the root level with the translations Rubric gave us, with the exception of the translation for "Command" where in de/fr, I replaced it with my own string just to test it saw new changes.

**Comment by theeagle** [comment]
Seeing this when building: 

Bildschirmfoto 2020-01-28 um 1 07 07 PM

**Comment by theeagle** [comment]
Bildschirmfoto 2020-01-28 um 1 08 25 PM

**Comment by jballance** [comment]
hmm. I wasn't getting any build errors before. when I check it out now, I get an error but its different than yours (says it cant copy the file because it doesnt exist)

when I converted them, xcode gave me an option to 'reinterpret' them with the new encoding, but it never actually made changes to the files.

**Comment by jballance** [comment]
it's happening on the first commit, pre encoding changes. I'm not sure what's going on

**Pull request merged**
